CREATE DATABASE REDDY;

USE REDDY;

CREATE TABLE MOBILE(
AMS_SHOPNAME VARCHAR(25),
AMS_ITEMS VARCHAR(30),
AMS_OWNERNAME VARCHAR(20),
AMS_ADDRESS VARCHAR(28),
AMS_PHONENO INT,
AMS_TIMINGS VARCHAR(40),
AMS_SERVICES VARCHAR(50),
AMS_ABOUT VARCHAR(29),
AMS_REVIEWS INT,
AMS_YEAROFESTABLISHMENT DATE
);

CREATE TABLE COUNTRY1 (
    Country_ID INT PRIMARY KEY,
    Country_Name VARCHAR(100),
    Capital VARCHAR(100),
    Population BIGINT,
    Area DOUBLE,
    Currency VARCHAR(50),
    Language VARCHAR(100),
    Continent VARCHAR(50),
    GDP BIGINT,
    President VARCHAR(100)
);

CREATE TABLE DECATHLON1 (
    Product_ID INT PRIMARY KEY,
    Product_Name VARCHAR(100),
    Category VARCHAR(50),
    Brand VARCHAR(50),
    Price DECIMAL(10, 2),
    Stock_Quantity INT,
    Description TEXT,
    Rating FLOAT,
    Discount DECIMAL(5, 2),
    Supplier VARCHAR(100)
);

CREATE TABLE ECOMMERCE1 (
    Product_ID INT PRIMARY KEY,
    Product_Name VARCHAR(100),
    Category VARCHAR(50),
    Brand VARCHAR(50),
    Price DECIMAL(10, 2),
    Stock_Quantity INT,
    Description TEXT,
    Rating FLOAT,
    Discount DECIMAL(5, 2),
    Seller VARCHAR(100)
);


CREATE TABLE HEALTHANDGLOW1 (
    Product_ID INT PRIMARY KEY,
    Product_Name VARCHAR(100),
    Brand VARCHAR(50),
    Category VARCHAR(50),
    Price DECIMAL(10, 2),
    Stock_Quantity INT,
    Expiry_Date DATE,
    Manufacturing_Date DATE,
    Description TEXT,
    Rating FLOAT
);


CREATE TABLE TRAINS1 (
    Train_ID INT PRIMARY KEY,
    Train_Name VARCHAR(100),
    Route VARCHAR(100),
    Departure_Time TIME,
    Arrival_Time TIME,
    Duration INT,
    Capacity INT,
    Available_Seats INT,
    Ticket_Price DECIMAL(10, 2),
    Class VARCHAR(50)
);


CREATE TABLE MOBILE_DETAILS1 (
    Mobile_ID INT PRIMARY KEY,
    Brand VARCHAR(50),
    Model VARCHAR(50),
    Storage INT,
    RAM INT,
    Processor VARCHAR(100),
    Display_Size FLOAT,
    Camera_Resolution INT,
    Battery_Capacity INT,
    Price DECIMAL(10, 2)
);


CREATE TABLE PETS_DETAILS1 (
    Pet_ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Species VARCHAR(50),
    Breed VARCHAR(50),
    Age INT,
    Color VARCHAR(50),
    Weight DECIMAL(6, 2),
    Owner_ID INT,
    Owner_Name VARCHAR(100),
    Vaccination_Status VARCHAR(50)
);


CREATE TABLE RESTAURANT1 (
    Restaurant_ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Cuisine VARCHAR(50),
    Location VARCHAR(100),
    Rating FLOAT,
    Opening_Hours VARCHAR(50),
    Contact_Number VARCHAR(15),
    Menu VARCHAR(255),
    Capacity INT,
    Price_Range VARCHAR(20)
);


CREATE TABLE STATIONARY_DETAILS1 (
    Item_ID INT PRIMARY KEY,
    Item_Name VARCHAR(100),
    Category VARCHAR(50),
    Brand VARCHAR(50),
    Color VARCHAR(50),
    Material VARCHAR(50),
    Stock_Quantity INT,
    Unit_Price DECIMAL(10, 2),
    Supplier_ID INT,
    Supplier_Name VARCHAR(100)
);


USE REDDY;
ALTER TABLE MOBILE RENAME TO DREDDY;
ALTER TABLE DREDDY RENAME COLUMN AMS_SHOPNAME TO AMS_NAME;
ALTER TABLE STATIONARY_DETAILS ADD COLUMN NAME VARCHAR(20);
ALTER TABLE RESTAURANT DROP COLUMN MENU;
ALTER TABLE MOBILE_DETAILS DROP COLUMN BRAND,DROP COLUMN MODEL;
ALTER TABLE RESTAURANT ADD COLUMN CUSTOMER VARCHAR(20); 
ALTER TABLE PETS_DETAILS MODIFY COLUMN BREED VARCHAR(50);

SELECT * FROM STATIONARY_DETAILS;
INSERT INTO STATIONARY_DETAILS VALUES('DP','PLASTIC','RR','MSPALYA','9880430755','5 TO 10','PENCIL','1980-04-29','DHANU');
SELECT * FROM STATIONARY_DETAILS;
